#!/usr/bin/env bash
_path=$(cd "${BASH_SOURCE[0]%/*}"; pwd)
. "$_path/../../lib/include.sh"

export SPIRE_CONFIG="$_path/_spire.json"
export OMNIA_CONFIG="$_path/omnia.conf"
export OMNIA_SOURCE_PARALLEL=1
export OMNIA_DEBUG=1

set -x

exportEthEnvs

jq --arg from "$ETH_FROM" --arg keys "$ETH_KEYSTORE" '.ethereum *= {from:$from,keystore:$keys}' "$_path/spire.json" > "$SPIRE_CONFIG"

startSSB
startLibp2p
startOmnia

oracle-transporter-spire pull 0x1f8fbe73820765677e68eb6e933dcb3c94c9b708 BALUSD
